---
#阿里云K8S系统初始化的时候会默认创建4个StorageClass，这4个StorageClass适合在集群类型为单一zone的情况，若为多zone部署的集群，则需要自己另行创建；
#licloud-disk-common：创建普通云盘。
#alicloud-disk-efficiency：创建高效云盘。
#alicloud-disk-ssd：创建SSD云盘。
#alicloud-disk-available：提供高可用选项，先试图创建高效云盘；如果相应AZ的高效云盘资源售尽，再试图创建SSD盘；如果SSD售尽，则试图创建普通云盘。
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: alicloud-disk-common-hangzhou-b
provisioner: alicloud/disk
reclaimPolicy: Retain
parameters:
  type: cloud_ssd
  regionid: cn-hangzhou
  zoneid: cn-hangzhou-b
  fstype: "ext4"
  readonly: "false"
  encrypted: "true"

#  reclaimPolicy：表示创建pv的回收策略，支持Delete、Retain两个类型，默认为Delete；这里需要注意：配置为Delete时，删除PVC后云盘一起被删除，数据不可恢复。
#
#  type: 表示创建什么类型的云盘，支持cloud、cloud_efficiency、cloud_ssd、available类型；
#
#  regionid：表示创建云盘所在region；
#
#  zoneid：表示创建云盘所在zone；
#
#  fstype：表示云盘使用的文件系统，可选项，默认为ext4；
#
#  readonly：表示挂载的读写权限是否为只读，可选项，默认为false；
#
#  encrypted：是否创建加密云盘，可选项，默认为false；
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-ssd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-ssd-beijing-b
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dynamic
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: disk-pvc
              mountPath: "/data"
      volumes:
        - name: disk-pvc
          persistentVolumeClaim:
            claimName: disk-ssd
